---
linters:
  enable:
    - godot
    - godox
    - gofmt
    - goimports
    - gosimple
    - ireturn
    - misspell
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nonamedreturns

linters-settings:
  ireturn:
    allow:
      - db.Error
      - error
      - net/http.Handler

run:
  issues-exit-code: 1
