# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go generate ./...
builds:
  - main: ./cmd/godent
    binary: godent
    ldflags:
      - -s
      - -w
      - -extldflags
      - -static
      - -X main.Commit={{.Commit}}
      - -X main.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
universal_binaries:
  - replace: true
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "tyrm/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "tyrm/{{ .ProjectName }}:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "tyrm/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "tyrm/{{ .ProjectName }}:latest-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  - name_template: tyrm/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - tyrm/{{ .ProjectName }}:{{ .Version }}-amd64
      - tyrm/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: tyrm/{{ .ProjectName }}:latest
    image_templates:
      - tyrm/{{ .ProjectName }}:latest-amd64
      - tyrm/{{ .ProjectName }}:latest-arm64v8
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-dev"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^deployments:'
